faster/cheaper build and format

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -56,21 +56,21 @@ jobs:
       - name: Cargo fmt
         run: cargo fmt --all --check
 
-  deny:
-    name: Deny
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        checks:
-          - advisories
-          - bans licenses sources
-    # Prevent new advisories from failing CI
-    continue-on-error: ${{ matrix.checks == 'advisories' }}
-    steps:
-      - uses: actions/checkout@v4
-      - uses: EmbarkStudios/cargo-deny-action@v2
-        with:
-          command: check ${{ matrix.checks }}
+  # deny:
+  #   name: Deny
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       checks:
+  #         - advisories
+  #         - bans licenses sources
+  #   # Prevent new advisories from failing CI
+  #   continue-on-error: ${{ matrix.checks == 'advisories' }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: EmbarkStudios/cargo-deny-action@v2
+  #       with:
+  #         command: check ${{ matrix.checks }}
 
   test:
     name: Test
@@ -243,100 +243,100 @@ jobs:
             target/${{ matrix.target_base || matrix.target }}/${{ env.BUILD_PROFILE }}/${{ env.CARGO_BIN_NAME }}.exe
           if-no-files-found: error
 
-  build-wasm:
-    name: Build objdiff-wasm
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Setup Rust toolchain
-        uses: dtolnay/rust-toolchain@nightly
-        with:
-          components: rust-src
-      - name: Cache Rust workspace
-        uses: Swatinem/rust-cache@v2
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: lts/*
-      - name: Install dependencies
-        run: npm -C objdiff-wasm ci
-      - name: Build
-        run: npm -C objdiff-wasm run build
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: wasm
-          path: objdiff-wasm/dist/
-          if-no-files-found: error
+  # build-wasm:
+  #   name: Build objdiff-wasm
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Setup Rust toolchain
+  #       uses: dtolnay/rust-toolchain@nightly
+  #       with:
+  #         components: rust-src
+  #     - name: Cache Rust workspace
+  #       uses: Swatinem/rust-cache@v2
+  #     - name: Setup Node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: lts/*
+  #     - name: Install dependencies
+  #       run: npm -C objdiff-wasm ci
+  #     - name: Build
+  #       run: npm -C objdiff-wasm run build
+  #     - name: Upload artifacts
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: wasm
+  #         path: objdiff-wasm/dist/
+  #         if-no-files-found: error
 
-  check-version:
-    name: Check package versions
-    if: startsWith(github.ref, 'refs/tags/')
-    runs-on: ubuntu-latest
-    needs: [ build-cli, build-gui, build-wasm ]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Check git tag against package versions
-        shell: bash
-        run: |
-          set -eou pipefail
-          tag='${{github.ref}}'
-          tag="${tag#refs/tags/}"
-          version=$(grep '^version' Cargo.toml | head -1 | awk -F' = ' '{print $2}' | tr -d '"')
-          version="v$version"
-          if [ "$tag" != "$version" ]; then
-            echo "::error::Git tag doesn't match the Cargo version! ($tag != $version)"
-            exit 1
-          fi
-          version="v$(jq -r .version objdiff-wasm/package.json)"
-          if [ "$tag" != "$version" ]; then
-            echo "::error::Git tag doesn't match the npm version! ($tag != $version)"
-            exit 1
-          fi
+  # check-version:
+  #   name: Check package versions
+  #   if: startsWith(github.ref, 'refs/tags/')
+  #   runs-on: ubuntu-latest
+  #   needs: [ build-cli, build-gui, build-wasm ]
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Check git tag against package versions
+  #       shell: bash
+  #       run: |
+  #         set -eou pipefail
+  #         tag='${{github.ref}}'
+  #         tag="${tag#refs/tags/}"
+  #         version=$(grep '^version' Cargo.toml | head -1 | awk -F' = ' '{print $2}' | tr -d '"')
+  #         version="v$version"
+  #         if [ "$tag" != "$version" ]; then
+  #           echo "::error::Git tag doesn't match the Cargo version! ($tag != $version)"
+  #           exit 1
+  #         fi
+  #         version="v$(jq -r .version objdiff-wasm/package.json)"
+  #         if [ "$tag" != "$version" ]; then
+  #           echo "::error::Git tag doesn't match the npm version! ($tag != $version)"
+  #           exit 1
+  #         fi
 
-  release-github:
-    name: Release (GitHub)
-    if: startsWith(github.ref, 'refs/tags/')
-    runs-on: ubuntu-latest
-    needs: [ check-version ]
-    permissions:
-      contents: write
-    steps:
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          pattern: objdiff-*
-          path: artifacts
-      - name: Rename artifacts
-        working-directory: artifacts
-        run: |
-          set -euo pipefail
-          mkdir ../out
-          for dir in */; do
-            for file in "$dir"*; do
-              base=$(basename "$file")
-              name="${base%.*}"
-              ext="${base##*.}"
-              if [ "$ext" = "$base" ]; then
-                  ext=""
-              else
-                  ext=".$ext"
-              fi
-              arch="${dir%/}" # remove trailing slash
-              arch="${arch##"$name-"}" # remove bin name
-              dst="../out/${name}-${arch}${ext}"
-              mv "$file" "$dst"
-            done
-          done
-          ls -R ../out
-      - name: Release
-        uses: softprops/action-gh-release@v2
-        with:
-          files: out/*
-          draft: true
-          generate_release_notes: true
+  # release-github:
+  #   name: Release (GitHub)
+  #   if: startsWith(github.ref, 'refs/tags/')
+  #   runs-on: ubuntu-latest
+  #   needs: [ check-version ]
+  #   permissions:
+  #     contents: write
+  #   steps:
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         pattern: objdiff-*
+  #         path: artifacts
+  #     - name: Rename artifacts
+  #       working-directory: artifacts
+  #       run: |
+  #         set -euo pipefail
+  #         mkdir ../out
+  #         for dir in */; do
+  #           for file in "$dir"*; do
+  #             base=$(basename "$file")
+  #             name="${base%.*}"
+  #             ext="${base##*.}"
+  #             if [ "$ext" = "$base" ]; then
+  #                 ext=""
+  #             else
+  #                 ext=".$ext"
+  #             fi
+  #             arch="${dir%/}" # remove trailing slash
+  #             arch="${arch##"$name-"}" # remove bin name
+  #             dst="../out/${name}-${arch}${ext}"
+  #             mv "$file" "$dst"
+  #           done
+  #         done
+  #         ls -R ../out
+  #     - name: Release
+  #       uses: softprops/action-gh-release@v2
+  #       with:
+  #         files: out/*
+  #         draft: true
+  #         generate_release_notes: true
 
   # release-cargo:
   #   name: Release (Cargo)
